import type { Meta, StoryObj } from '@storybook/vue3-vite'
import { defineComponent, h, onMounted } from 'vue'
import { useQuasar } from 'quasar'
import arLang from 'quasar/lang/ar'
import NsButton from '../components/NsButton/NsButton.vue'
import NsSkeleton from '../components/NsSkeleton/NsSkeleton.vue'

/**
 * RTL (Right-to-Left) stories verify that components render correctly
 * when Quasar is loaded with an RTL language pack like Arabic.
 *
 * Quasar handles RTL automatically — components flip layout direction
 * via `[dir=rtl]` CSS selectors generated by postcss-rtlcss.
 */

const RtlWrapper = defineComponent({
  props: {
    rtl: { type: Boolean, default: true },
  },
  setup(props, { slots }) {
    const $q = useQuasar()

    onMounted(() => {
      if (props.rtl) {
        $q.lang.set(arLang)
        document.documentElement.setAttribute('dir', 'rtl')
      }
    })

    return () =>
      h(
        'div',
        { dir: props.rtl ? 'rtl' : 'ltr', style: 'padding: 24px; font-family: sans-serif;' },
        slots.default?.(),
      )
  },
})

const meta = {
  title: 'Utilities/RTL Support',
  component: RtlWrapper,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          'Verifies that components render correctly in RTL mode. ' +
          'Quasar automatically flips directional CSS when an RTL language pack is loaded.',
      },
    },
  },
} satisfies Meta<typeof RtlWrapper>

export default meta
type Story = StoryObj<typeof meta>

export const ButtonsRTL: Story = {
  name: 'Buttons (Arabic)',
  render: () => ({
    components: { RtlWrapper, NsButton },
    template: `
      <RtlWrapper>
        <div style="display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 16px;">
          <NsButton color="primary" icon="arrow_back">رجوع</NsButton>
          <NsButton color="secondary" icon-right="arrow_forward">التالي</NsButton>
          <NsButton color="accent" icon="shopping_cart">أضف إلى السلة</NsButton>
        </div>
        <div style="display: flex; gap: 12px; flex-wrap: wrap;">
          <NsButton color="primary" loading>جاري التحميل</NsButton>
          <NsButton color="positive">حفظ</NsButton>
          <NsButton color="negative">حذف</NsButton>
        </div>
      </RtlWrapper>
    `,
  }),
}

export const SkeletonsRTL: Story = {
  name: 'Skeletons (Arabic)',
  render: () => ({
    components: { RtlWrapper, NsSkeleton },
    template: `
      <RtlWrapper>
        <div style="width: 350px;">
          <div style="display: flex; gap: 12px; margin-bottom: 16px; align-items: center;">
            <NsSkeleton type="QAvatar" />
            <div style="flex: 1;">
              <NsSkeleton type="text" style="margin-bottom: 6px;" />
              <NsSkeleton type="text" width="60%" />
            </div>
          </div>
          <NsSkeleton type="rect" height="150px" style="margin-bottom: 12px;" />
          <div style="display: flex; gap: 8px; justify-content: flex-start;">
            <NsSkeleton type="QBtn" />
            <NsSkeleton type="QBtn" />
          </div>
        </div>
      </RtlWrapper>
    `,
  }),
}

export const LTRComparison: Story = {
  name: 'LTR vs RTL Comparison',
  render: () => ({
    components: { RtlWrapper, NsButton },
    template: `
      <div style="display: flex; gap: 32px;">
        <div>
          <h4 style="margin: 0 0 12px;">LTR (English)</h4>
          <div dir="ltr" style="padding: 16px; border: 1px solid #e0e0e0; border-radius: 8px;">
            <div style="display: flex; gap: 8px;">
              <NsButton icon="arrow_back">Back</NsButton>
              <NsButton icon-right="arrow_forward">Next</NsButton>
            </div>
          </div>
        </div>
        <div>
          <h4 style="margin: 0 0 12px;">RTL (العربية)</h4>
          <RtlWrapper>
            <div style="padding: 16px; border: 1px solid #e0e0e0; border-radius: 8px;">
              <div style="display: flex; gap: 8px;">
                <NsButton icon="arrow_back">رجوع</NsButton>
                <NsButton icon-right="arrow_forward">التالي</NsButton>
              </div>
            </div>
          </RtlWrapper>
        </div>
      </div>
    `,
  }),
}
